### ISSUE TITLE
Typescript example

### ISSUE THREAD

**Issue by toinbis** [lukeed/tempura#9]
Would be cool to have one example with https://github.com/cloudflare/worker-typescript-template as basis.

Thanks!

**Comment by lukeed** [comment]
Hey, didn't use the whole repo because the entire setup isn't really relevant. It should work in any TS configuration. For this, I even just added `ts-check` to turn on VS Code Intellisense. 

Making this example exposed a slight bug/annoyance in the type definitions, so thanks for this :)

Hope it helps

**Comment by toinbis** [comment]
That was quick! :) Thanks, @lukeed ! Will try it and will let you know here if all went well! :)
